{% set name = "local-migrator" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54e75c0fa4527c1c40cf429308d3eeab714d510c5ce67d94fbcb5e06ac8b39f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - packaging

test:
  imports:
    - local_migrator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/local-migrator/
  summary: Package for simplify data structures migrations
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/Czaki/local_migrator/

extra:
  recipe-maintainers:
    - Czaki
